export const tableColumns = [
    'STT',
    'Họ và Tên',
    'Ngày sinh',
    'Giới tính',
    'Email',
    'Số điện thoại',
    'Người tạo',
    'Ngày tạo',
    'Nguồn',
    'Ngành nghề',
    'Số CCCD/CMND',
    'Tình trạng hôn nhân',
    'Chiều cao(cm)',
    'Cân nặng(kg)',
    'Nơi ở hiện tại',
    'Kỹ năng',
    'Mức lương mong muốn',
    'Nơi làm việc mong muốn',
    'Số năm kinh nghiệm',
    'Quê quán',
    'Học vấn',
    'Kinh nghiệm làm việc ',
    'Ngày ứng tuyển',
    'Người phụ trách tin',
    'Tin tuyển dụng',
    'Đơn vị',
    'Vị trí công việc',
    'Bước tuyển dụng',
    'Điểm trung bình ',
    'Ngày thi',
    'Điểm thi',
    'Ngày phỏng vấn lần 1',
    'Kết quả phỏng vấn lần 1',
    'Ngày phỏng vấn lần 2',
    'Kết quả phỏng vấn lần 2',
    'Ngày phỏng vấn lần 3',
    'Kết quả phỏng vấn lần 3',
    'Ngày phỏng vấn lần 4',
    'Kết quả phỏng vấn lần 4',
    'Ngày phỏng vấn lần 5',
    'Kết quả phỏng vấn lần 5',
]