export const recruitmentColumns = [
    'STT',
    'Tin tuyển dụng',
    'Vị trí công việc',
    'Đơn vị',
    'Trạng thái',
    'Ngày bắt đầu',
    'Ngày hết hạn',
    'Ngày tạo tin',
    'SL ứng tuyển',
    'SL cần tuyển',
    'SL đạt',
    'SL nhận việc',
    'Cán bộ phụ trách',
    'Đồng phụ trách',
    'Khu vực đăng tin',
    'Hình thức làm việc',
    'Mức lương',
    'Chức danh',
    'Số năm kinh nghiệm',
    'Ngôn ngữ',
]