name: Deploy to Docker hub
'on':
  push:
    branches:
      - develop_inside
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker-compose -f docker-compose.yml build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Push Docker Image to docker hub
        run: docker-compose push
  deploy_hosted_machine:
    name: Deploy Inside service
    timeout-minutes: 15
    needs: [ build_and_deploy ]
    runs-on: self-hosted
    steps:
      - name: Pulling Inside docker image
        run: docker pull thuybon1/iviec_inside:1.0.0

      - name: Deploy Inside Iviec service
        working-directory: /root/iViec_Fe
        run: docker-compose up -d iviec_inside
