name: Deploy to Docker hub
'on':
  push:
    branches:
      - develop_dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker-compose -f docker-compose.yml build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Push Docker Image to docker hub
        run: docker-compose push
